#!/usr/bin/env python

#****************************************************
# Class for manipulating wifi interfaces
# Input: 
#   -i, iface:      wireless interface name
#   -c, channels:   channels to survey
#   -f, filter:     filter applied to received packets
# Output:
#   -stream of captured packets
#****************************************************

from __future__ import print_function
import sys
import os
import subprocess

def execute_retry(cmd, max_counter = 10):
    counter = 0
    print("{:40s} ".format(cmd), end="\t")
    while os.system(cmd):
        counter += 1
        print("\n[{:02d}/{:02d}] {:s} Failed".format(counter, max_counter, cmd),end="")
        if counter >  max_counter : print('\n[Error] Max trial reached'); return 1    
    print("OK")    
    return 0

class WiFiDevice:
    """
    Base class to listen wireless devices
    """
    def __init__(self,**kwargs):
        self.iface = kwargs.get('iface','wlp5s0')
        self.channels = kwargs.get('channels', (1,6,11))
        self.chopper_ts = kwargs.get('channel_hopper_sampling_time',1.0)
        self.filter = kwargs.get('filter','Beacon')

        self.isCHopperRunning = False # Channel hopper running flag
        self.isTcpdumpRunning = False # Packages being acquired
        self.tcpdump_process  = None

        if self.init_device() == 0: print('\nDevice Initialized')
        else: return 1;
    
    def init_device(self):
        # turn the interface on/off to reset
        if execute_retry("sudo -S ifconfig {:s} down".format(self.iface)) != 0          : return 1
        if execute_retry("sudo -S ifconfig {:s} up".format(self.iface)) != 0            : return 1
        # set interface to default channel (1) 
        if execute_retry("sudo -S iwconfig {:s} channel 1".format(self.iface)) != 0     : return 1
        # change interface to monitor mode (off -> monitor mode -> on)
        if execute_retry("sudo -S ifconfig {:s} down".format(self.iface)) != 0          : return 1
        if execute_retry("sudo -S iwconfig {:s} mode monitor".format(self.iface)) != 0  : return 1
        if execute_retry("sudo -S ifconfig {:s} up".format(self.iface)) != 0            : return 1
        return 0

    def chopper_start(self):
        self.cmd = "python channel_hopper.py -i {} -t {} -ch {}".format(self.iface,1.*self.chopper_ts," ".join(str(ch) for ch in self.channels))
        self.isCHopperRunning = True        
        #try:
        subprocess.Popen(self.cmd.split(),stdout=subprocess.PIPE)
        #except:
        #self.isCHopperRunning = False
        #print('[Error] Channel Hopper unexpectedly stopped')

    def tcpdump_start(self):
        """
        iface must be initialized before with init(iface)
        """
        cmd = 'sudo -S tcpdump -i {:s} -ne --time-stamp-precision=micro -l --immediate-mode type mgt subtype beacon'.format(self.iface)
        self.tcpdump_process = subprocess.Popen(cmd.split(),stdout=subprocess.PIPE)
        self.isTcpdumpRunning = True
